# K-ECP SSO - 운영 환경
# HTTPS 활성화, 보안 강화
#
# 사용법:
#   podman-compose -f compose.prod.yml up -d

services:
  keycloak-db:
    image: docker.io/postgres:15-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - kecp-sso-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    environment:
      # Database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      # Server
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_STRICT: "true"
      KC_HTTP_ENABLED: "false"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
      KC_PROXY_HEADERS: xforwarded
      # Features
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      # Admin (운영에서는 별도 관리)
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes:ro
      - ./keycloak/certs:/opt/keycloak/conf:ro
    ports:
      - "${KEYCLOAK_PORT:-8443}:8443"
    networks:
      - kecp-sso-network
    depends_on:
      keycloak-db:
        condition: service_healthy
    command: start
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  keycloak-db-data:

networks:
  kecp-sso-network:
    driver: bridge
